#!/usr/bin/env bash
#Install and configure Nginx
apt-get install nginx -y
service nginx start
echo "Hello World!" > /var/www/html/ret_file.html
echo "Ceci n'est pas une page" > /var/www/html/custom_404.html

#Configure nginx to serve the file
echo "server {
   listen 80;
   listen [::]:80;
   root /var/www/html;
   index ret_file.html;

   location /redirect_me {
     return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
  }
   error_page 404 /custom_404.html;
   location = /custom_404.html {
    internal;
  }
}" > /etc/nginx/sites-available/default
service nginx restart
